charset: "UTF-8"
layout: "main"
template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'
auto_page: 1
passwd_salt: "j$jz#&vz9(3$f.;P"
passwd_file: passwd
